spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/demo_crud_spring_boot?serverTimezone=Asia/Jakarta
    username: root
    password: root
server:
  port: 9090
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

servlet:
  multipart:
    enabled: true
    max-file: 32MB
    max-request: 32MB
  session:
    timeout: 120m
logging:
  level:
    root: INFO